#!/usr/bin/env node


var op = process.argv[2];
var n1 = +(process.argv[3]);
var n2 = +(process.argv[4]);

if (op === "add" || op === "+"){
	console.log(n1 + n2)
}
else if (op === "sub" || op === "-"){
	console.log(n1 - n2)
}
// 	TODO: does NOT 
else if (op === "mult" || op === "*"){
	console.log(n1 * n2)
}
else if (op === "div" || op === "/"){
	console.log(n1 / n2)
}
